/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university;

/**
 *
 * @author ahmed
 */
public class EditCourse extends javax.swing.JFrame {

    /**
     * Creates new form EditCourse
     */
    public EditCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label0 = new javax.swing.JLabel();
        lable1 = new javax.swing.JLabel();
        E_C_code = new javax.swing.JTextField();
        E_C_name = new javax.swing.JTextField();
        lable2 = new javax.swing.JLabel();
        lable3 = new javax.swing.JLabel();
        E_C_h = new javax.swing.JTextField();
        E_t_name = new javax.swing.JTextField();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        E_Salary = new javax.swing.JTextField();
        semaster = new javax.swing.JTextField();
        Label6 = new javax.swing.JLabel();
        EButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Label0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label0.setText("EditCourse");

        lable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lable1.setText("CourseCode");

        E_C_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_C_codeActionPerformed(evt);
            }
        });

        E_C_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_C_nameActionPerformed(evt);
            }
        });

        lable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lable2.setText("CourseName");

        lable3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lable3.setText("CourseHours");

        E_C_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_C_hActionPerformed(evt);
            }
        });

        E_t_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_t_nameActionPerformed(evt);
            }
        });

        Label4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label4.setText("TeatcherName");

        Label5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label5.setText("SalaryOnHour");

        E_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_SalaryActionPerformed(evt);
            }
        });

        semaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semasterActionPerformed(evt);
            }
        });

        Label6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label6.setText("Semester");

        EButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EButton.setText("Edit");
        EButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lable3)
                                .addGap(18, 18, 18)
                                .addComponent(E_C_h, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lable2)
                                    .addGap(18, 18, 18)
                                    .addComponent(E_C_name, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lable1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(E_C_code, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label4)
                                .addGap(18, 18, 18)
                                .addComponent(E_t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label5)
                                .addGap(18, 18, 18)
                                .addComponent(E_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label6)
                                .addGap(18, 18, 18)
                                .addComponent(semaster, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(218, 218, 218)
                            .addComponent(EButton)))
                    .addComponent(Label0))
                .addGap(222, 222, 222))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Label0)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lable1)
                    .addComponent(E_C_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lable2)
                    .addComponent(E_C_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lable3)
                    .addComponent(E_C_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label4)
                    .addComponent(E_t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label5)
                    .addComponent(E_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label6)
                    .addComponent(semaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(EButton)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setSize(new java.awt.Dimension(550, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void E_C_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_C_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_C_codeActionPerformed

    private void E_C_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_C_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_C_nameActionPerformed

    private void E_C_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_C_hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_C_hActionPerformed

    private void E_t_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_t_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_t_nameActionPerformed

    private void E_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_SalaryActionPerformed

    private void semasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semasterActionPerformed

    private void EButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonActionPerformed
        if(E_C_code.getText().equals("")||E_C_name.getText().equals("")||E_C_h.getText().equals("")||E_Salary.getText().equals("")||E_t_name.getText().equals("")||semaster.getText().equals("")){
            JOptionPane.showMessageDialog(null, " data is uncomplete");

        }else{
            try{
                int CID=Integer.parseInt(E_C_code.getText().trim());
                int salar=Integer.parseInt(E_Salary.getText().trim());
                int Semaster=Integer.parseInt(semaster.getText().trim());
                int CHour=Integer.parseInt(E_C_h.getText().trim());

                if(!(Semaster==1||Semaster==2)){

                    JOptionPane.showMessageDialog(null, "semaster mustr be 1 or 2");

                }
                if(CID>=1){
                    try {
                        con=connectionDataBase.connect();
                        com=con.prepareStatement("select *from course  where  C_id='"+CID+"'");
                        res=com.executeQuery();
                        if(res.next()){
                            JOptionPane.showMessageDialog(null, "the course is alrady exist");

                        }else{
                            try{
                                // com=con.prepareStatement("insert into Doctor values('"+DID+"','"+D_Name.getText()+"','"+D_password.getText()+"','"+D_Mobile.getText()+"','"+"suez"+"','"+g+"')");

                                com  = con.prepareStatement("INSERT INTO course(C_id,course_name,hour,salaryOnHour,semester) VALUES ("
                                    + "'" + CID +"',"
                                    + "'" + E_C_name.getText() +"',"
                                    + "'" + CHour +"',"
                                    + "'" + salar +"',"
                                    + "'" + Semaster +"'"
                                    +")");

                                com.execute();
                                JOptionPane.showMessageDialog(null, " course added ");
                                clean();

                            }catch(HeadlessException | SQLException e){
                                System.out.println(e);

                            }

                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(AddDoctor.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }else{
                    JOptionPane.showMessageDialog(null, " course id must be in the range greater than 1");
                }

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "invalid data");
            }finally{
                try {
                    con.close();
                } catch (SQLException ex) {
                    Logger.getLogger(AddDoctor.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }

    }//GEN-LAST:event_EButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton EButton;
    private javax.swing.JTextField E_C_code;
    public javax.swing.JTextField E_C_h;
    public javax.swing.JTextField E_C_name;
    public javax.swing.JTextField E_Salary;
    public javax.swing.JTextField E_t_name;
    private javax.swing.JLabel Label0;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lable1;
    private javax.swing.JLabel lable2;
    private javax.swing.JLabel lable3;
    public javax.swing.JTextField semaster;
    // End of variables declaration//GEN-END:variables
}
